# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traceAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1058, 884)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
		self.horizontalLayoutWidget.setGeometry(QtCore.QRect(610, 30, 411, 151))
		self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.masterLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.masterLabel.setObjectName("masterLabel")
		self.horizontalLayout.addWidget(self.masterLabel)
		self.FilePathText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
		self.FilePathText.setReadOnly(True)
		self.FilePathText.setObjectName("FilePathText")
		self.horizontalLayout.addWidget(self.FilePathText)
		self.BrowseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
		self.BrowseButton.setObjectName("BrowseButton")
		self.horizontalLayout.addWidget(self.BrowseButton)
		self.LoadButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
		self.LoadButton.setEnabled(False)
		self.LoadButton.setObjectName("LoadButton")
		self.horizontalLayout.addWidget(self.LoadButton)
		self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
		self.scrollArea.setGeometry(QtCore.QRect(10, 20, 591, 711))
		self.scrollArea.setWidgetResizable(True)
		self.scrollArea.setObjectName("scrollArea")
		self.scrollAreaWidgetContents = QtWidgets.QWidget()
		self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 575, 1764))
		self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
		self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
		self.gridLayout.setContentsMargins(0, 0, 0, 0)
		self.gridLayout.setObjectName("gridLayout")
		self.masterReadout = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
		self.masterReadout.setObjectName("masterReadout")
		self.masterTab = QtWidgets.QWidget()
		self.masterTab.setObjectName("masterTab")
		self.formLayout = QtWidgets.QFormLayout(self.masterTab)
		self.formLayout.setContentsMargins(0, 0, 0, 0)
		self.formLayout.setObjectName("formLayout")
		self.GeneralLabel = QtWidgets.QLabel(self.masterTab)
		self.GeneralLabel.setObjectName("GeneralLabel")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.GeneralLabel)
		self.workingDirLabel = QtWidgets.QLabel(self.masterTab)
		self.workingDirLabel.setObjectName("workingDirLabel")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.workingDirLabel)
		self.workingDirRO = QtWidgets.QLineEdit(self.masterTab)
		self.workingDirRO.setReadOnly(True)
		self.workingDirRO.setObjectName("workingDirRO")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.workingDirRO)
		self.dataDirLabel = QtWidgets.QLabel(self.masterTab)
		self.dataDirLabel.setObjectName("dataDirLabel")
		self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dataDirLabel)
		self.dataDirRO = QtWidgets.QLineEdit(self.masterTab)
		self.dataDirRO.setReadOnly(True)
		self.dataDirRO.setObjectName("dataDirRO")
		self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dataDirRO)
		self.plotsDirLabel = QtWidgets.QLabel(self.masterTab)
		self.plotsDirLabel.setObjectName("plotsDirLabel")
		self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.plotsDirLabel)
		self.plotsDirRO = QtWidgets.QLineEdit(self.masterTab)
		self.plotsDirRO.setReadOnly(True)
		self.plotsDirRO.setObjectName("plotsDirRO")
		self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.plotsDirRO)
		self.traceDirLabel = QtWidgets.QLabel(self.masterTab)
		self.traceDirLabel.setObjectName("traceDirLabel")
		self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.traceDirLabel)
		self.traceDirRO = QtWidgets.QLineEdit(self.masterTab)
		self.traceDirRO.setReadOnly(True)
		self.traceDirRO.setObjectName("traceDirRO")
		self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.traceDirRO)
		self.ansiColorsLabel = QtWidgets.QLabel(self.masterTab)
		self.ansiColorsLabel.setObjectName("ansiColorsLabel")
		self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.ansiColorsLabel)
		self.ansiColorsRO = QtWidgets.QLineEdit(self.masterTab)
		self.ansiColorsRO.setReadOnly(True)
		self.ansiColorsRO.setObjectName("ansiColorsRO")
		self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ansiColorsRO)
		self.doPlotsLabel = QtWidgets.QLabel(self.masterTab)
		self.doPlotsLabel.setObjectName("doPlotsLabel")
		self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.doPlotsLabel)
		self.doPlotsRO = QtWidgets.QLineEdit(self.masterTab)
		self.doPlotsRO.setReadOnly(True)
		self.doPlotsRO.setObjectName("doPlotsRO")
		self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.doPlotsRO)
		self.IOLabel = QtWidgets.QLabel(self.masterTab)
		self.IOLabel.setObjectName("IOLabel")
		self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.IOLabel)
		self.saveDataLabel = QtWidgets.QLabel(self.masterTab)
		self.saveDataLabel.setObjectName("saveDataLabel")
		self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.saveDataLabel)
		self.saveDataRO = QtWidgets.QLineEdit(self.masterTab)
		self.saveDataRO.setReadOnly(True)
		self.saveDataRO.setObjectName("saveDataRO")
		self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.saveDataRO)
		self.saveToLabel = QtWidgets.QLabel(self.masterTab)
		self.saveToLabel.setObjectName("saveToLabel")
		self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.saveToLabel)
		self.saveToRO = QtWidgets.QLineEdit(self.masterTab)
		self.saveToRO.setReadOnly(True)
		self.saveToRO.setObjectName("saveToRO")
		self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.saveToRO)
		self.loadLabel = QtWidgets.QLabel(self.masterTab)
		self.loadLabel.setObjectName("loadLabel")
		self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.loadLabel)
		self.loadRO = QtWidgets.QLineEdit(self.masterTab)
		self.loadRO.setReadOnly(True)
		self.loadRO.setObjectName("loadRO")
		self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.loadRO)
		self.loadFromLabel = QtWidgets.QLabel(self.masterTab)
		self.loadFromLabel.setObjectName("loadFromLabel")
		self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.loadFromLabel)
		self.loadFromRO = QtWidgets.QLineEdit(self.masterTab)
		self.loadFromRO.setReadOnly(True)
		self.loadFromRO.setObjectName("loadFromRO")
		self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.loadFromRO)
		self.showPlotsLabel = QtWidgets.QLabel(self.masterTab)
		self.showPlotsLabel.setObjectName("showPlotsLabel")
		self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.showPlotsLabel)
		self.showPlotsRO = QtWidgets.QLineEdit(self.masterTab)
		self.showPlotsRO.setReadOnly(True)
		self.showPlotsRO.setObjectName("showPlotsRO")
		self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.showPlotsRO)
		self.savePlotsLabel = QtWidgets.QLabel(self.masterTab)
		self.savePlotsLabel.setObjectName("savePlotsLabel")
		self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.savePlotsLabel)
		self.savePlotsRO = QtWidgets.QLineEdit(self.masterTab)
		self.savePlotsRO.setReadOnly(True)
		self.savePlotsRO.setObjectName("savePlotsRO")
		self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.savePlotsRO)
		self.allPlotsLabel = QtWidgets.QLabel(self.masterTab)
		self.allPlotsLabel.setObjectName("allPlotsLabel")
		self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.allPlotsLabel)
		self.allPlotsRO = QtWidgets.QLineEdit(self.masterTab)
		self.allPlotsRO.setReadOnly(True)
		self.allPlotsRO.setObjectName("allPlotsRO")
		self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.allPlotsRO)
		self.ChannelLabel = QtWidgets.QLabel(self.masterTab)
		self.ChannelLabel.setObjectName("ChannelLabel")
		self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.ChannelLabel)
		self.doubleChannelLabel = QtWidgets.QLabel(self.masterTab)
		self.doubleChannelLabel.setObjectName("doubleChannelLabel")
		self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.doubleChannelLabel)
		self.BGSubtractionLabel = QtWidgets.QLabel(self.masterTab)
		self.BGSubtractionLabel.setObjectName("BGSubtractionLabel")
		self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.BGSubtractionLabel)
		self.channel1Label = QtWidgets.QLabel(self.masterTab)
		self.channel1Label.setObjectName("channel1Label")
		self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.channel1Label)
		self.channel2Label = QtWidgets.QLabel(self.masterTab)
		self.channel2Label.setObjectName("channel2Label")
		self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.channel2Label)
		self.metaLabel = QtWidgets.QLabel(self.masterTab)
		self.metaLabel.setObjectName("metaLabel")
		self.formLayout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.metaLabel)
		self.channelBGLabel = QtWidgets.QLabel(self.masterTab)
		self.channelBGLabel.setObjectName("channelBGLabel")
		self.formLayout.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.channelBGLabel)
		self.channel2BGLabel = QtWidgets.QLabel(self.masterTab)
		self.channel2BGLabel.setObjectName("channel2BGLabel")
		self.formLayout.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.channel2BGLabel)
		self.metaBG = QtWidgets.QLabel(self.masterTab)
		self.metaBG.setObjectName("metaBG")
		self.formLayout.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.metaBG)
		self.doubleChannelRO = QtWidgets.QLineEdit(self.masterTab)
		self.doubleChannelRO.setReadOnly(True)
		self.doubleChannelRO.setObjectName("doubleChannelRO")
		self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.doubleChannelRO)
		self.BGSubtractionRO = QtWidgets.QLineEdit(self.masterTab)
		self.BGSubtractionRO.setReadOnly(True)
		self.BGSubtractionRO.setObjectName("BGSubtractionRO")
		self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.BGSubtractionRO)
		self.channel1RO = QtWidgets.QLineEdit(self.masterTab)
		self.channel1RO.setReadOnly(True)
		self.channel1RO.setObjectName("channel1RO")
		self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.channel1RO)
		self.channel2RO = QtWidgets.QLineEdit(self.masterTab)
		self.channel2RO.setReadOnly(True)
		self.channel2RO.setObjectName("channel2RO")
		self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.channel2RO)
		self.metaRO = QtWidgets.QLineEdit(self.masterTab)
		self.metaRO.setReadOnly(True)
		self.metaRO.setObjectName("metaRO")
		self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.metaRO)
		self.channel1BGRO = QtWidgets.QLineEdit(self.masterTab)
		self.channel1BGRO.setReadOnly(True)
		self.channel1BGRO.setObjectName("channel1BGRO")
		self.formLayout.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.channel1BGRO)
		self.channel2BGRO = QtWidgets.QLineEdit(self.masterTab)
		self.channel2BGRO.setReadOnly(True)
		self.channel2BGRO.setObjectName("channel2BGRO")
		self.formLayout.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.channel2BGRO)
		self.metaBGRO = QtWidgets.QLineEdit(self.masterTab)
		self.metaBGRO.setReadOnly(True)
		self.metaBGRO.setObjectName("metaBGRO")
		self.formLayout.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.metaBGRO)
		self.WindowLabel = QtWidgets.QLabel(self.masterTab)
		self.WindowLabel.setObjectName("WindowLabel")
		self.formLayout.setWidget(25, QtWidgets.QFormLayout.LabelRole, self.WindowLabel)
		self.xPlotTypeLabel = QtWidgets.QLabel(self.masterTab)
		self.xPlotTypeLabel.setObjectName("xPlotTypeLabel")
		self.formLayout.setWidget(26, QtWidgets.QFormLayout.LabelRole, self.xPlotTypeLabel)
		self.yPlotTypeLabel = QtWidgets.QLabel(self.masterTab)
		self.yPlotTypeLabel.setObjectName("yPlotTypeLabel")
		self.formLayout.setWidget(27, QtWidgets.QFormLayout.LabelRole, self.yPlotTypeLabel)
		self.xRelativeGridLabel = QtWidgets.QLabel(self.masterTab)
		self.xRelativeGridLabel.setObjectName("xRelativeGridLabel")
		self.formLayout.setWidget(28, QtWidgets.QFormLayout.LabelRole, self.xRelativeGridLabel)
		self.xPlotTypeRO = QtWidgets.QLineEdit(self.masterTab)
		self.xPlotTypeRO.setReadOnly(True)
		self.xPlotTypeRO.setObjectName("xPlotTypeRO")
		self.formLayout.setWidget(26, QtWidgets.QFormLayout.FieldRole, self.xPlotTypeRO)
		self.yPlotTypeRO = QtWidgets.QLineEdit(self.masterTab)
		self.yPlotTypeRO.setReadOnly(True)
		self.yPlotTypeRO.setObjectName("yPlotTypeRO")
		self.formLayout.setWidget(27, QtWidgets.QFormLayout.FieldRole, self.yPlotTypeRO)
		self.xRelativeGridRO = QtWidgets.QLineEdit(self.masterTab)
		self.xRelativeGridRO.setReadOnly(True)
		self.xRelativeGridRO.setObjectName("xRelativeGridRO")
		self.formLayout.setWidget(28, QtWidgets.QFormLayout.FieldRole, self.xRelativeGridRO)
		self.IntegrationLabel = QtWidgets.QLabel(self.masterTab)
		self.IntegrationLabel.setObjectName("IntegrationLabel")
		self.formLayout.setWidget(29, QtWidgets.QFormLayout.LabelRole, self.IntegrationLabel)
		self.SILLabel = QtWidgets.QLabel(self.masterTab)
		self.SILLabel.setObjectName("SILLabel")
		self.formLayout.setWidget(30, QtWidgets.QFormLayout.LabelRole, self.SILLabel)
		self.SIULabel = QtWidgets.QLabel(self.masterTab)
		self.SIULabel.setObjectName("SIULabel")
		self.formLayout.setWidget(31, QtWidgets.QFormLayout.LabelRole, self.SIULabel)
		self.PILLabel = QtWidgets.QLabel(self.masterTab)
		self.PILLabel.setObjectName("PILLabel")
		self.formLayout.setWidget(32, QtWidgets.QFormLayout.LabelRole, self.PILLabel)
		self.PIULabel = QtWidgets.QLabel(self.masterTab)
		self.PIULabel.setObjectName("PIULabel")
		self.formLayout.setWidget(33, QtWidgets.QFormLayout.LabelRole, self.PIULabel)
		self.SILRO = QtWidgets.QLineEdit(self.masterTab)
		self.SILRO.setReadOnly(True)
		self.SILRO.setObjectName("SILRO")
		self.formLayout.setWidget(30, QtWidgets.QFormLayout.FieldRole, self.SILRO)
		self.SIURO = QtWidgets.QLineEdit(self.masterTab)
		self.SIURO.setReadOnly(True)
		self.SIURO.setObjectName("SIURO")
		self.formLayout.setWidget(31, QtWidgets.QFormLayout.FieldRole, self.SIURO)
		self.PILRO = QtWidgets.QLineEdit(self.masterTab)
		self.PILRO.setReadOnly(True)
		self.PILRO.setObjectName("PILRO")
		self.formLayout.setWidget(32, QtWidgets.QFormLayout.FieldRole, self.PILRO)
		self.PIURO = QtWidgets.QLineEdit(self.masterTab)
		self.PIURO.setReadOnly(True)
		self.PIURO.setObjectName("PIURO")
		self.formLayout.setWidget(33, QtWidgets.QFormLayout.FieldRole, self.PIURO)
		self.SpikeRejectionLabel = QtWidgets.QLabel(self.masterTab)
		self.SpikeRejectionLabel.setObjectName("SpikeRejectionLabel")
		self.formLayout.setWidget(34, QtWidgets.QFormLayout.LabelRole, self.SpikeRejectionLabel)
		self.doSpikeRejectionLabel = QtWidgets.QLabel(self.masterTab)
		self.doSpikeRejectionLabel.setObjectName("doSpikeRejectionLabel")
		self.formLayout.setWidget(35, QtWidgets.QFormLayout.LabelRole, self.doSpikeRejectionLabel)
		self.voltageThreshholdLabel = QtWidgets.QLabel(self.masterTab)
		self.voltageThreshholdLabel.setObjectName("voltageThreshholdLabel")
		self.formLayout.setWidget(36, QtWidgets.QFormLayout.LabelRole, self.voltageThreshholdLabel)
		self.timeThresholdLabel = QtWidgets.QLabel(self.masterTab)
		self.timeThresholdLabel.setObjectName("timeThresholdLabel")
		self.formLayout.setWidget(37, QtWidgets.QFormLayout.LabelRole, self.timeThresholdLabel)
		self.doSpikeRejectionRO = QtWidgets.QLineEdit(self.masterTab)
		self.doSpikeRejectionRO.setReadOnly(True)
		self.doSpikeRejectionRO.setObjectName("doSpikeRejectionRO")
		self.formLayout.setWidget(35, QtWidgets.QFormLayout.FieldRole, self.doSpikeRejectionRO)
		self.voltageThresholdRO = QtWidgets.QLineEdit(self.masterTab)
		self.voltageThresholdRO.setReadOnly(True)
		self.voltageThresholdRO.setObjectName("voltageThresholdRO")
		self.formLayout.setWidget(36, QtWidgets.QFormLayout.FieldRole, self.voltageThresholdRO)
		self.timeThresholdRO = QtWidgets.QLineEdit(self.masterTab)
		self.timeThresholdRO.setReadOnly(True)
		self.timeThresholdRO.setObjectName("timeThresholdRO")
		self.formLayout.setWidget(37, QtWidgets.QFormLayout.FieldRole, self.timeThresholdRO)
		self.SmoothedDoubleRejectionLabel = QtWidgets.QLabel(self.masterTab)
		self.SmoothedDoubleRejectionLabel.setObjectName("SmoothedDoubleRejectionLabel")
		self.formLayout.setWidget(38, QtWidgets.QFormLayout.LabelRole, self.SmoothedDoubleRejectionLabel)
		self.doDoubleRejectionLabel = QtWidgets.QLabel(self.masterTab)
		self.doDoubleRejectionLabel.setObjectName("doDoubleRejectionLabel")
		self.formLayout.setWidget(39, QtWidgets.QFormLayout.LabelRole, self.doDoubleRejectionLabel)
		self.SGWindowLabel = QtWidgets.QLabel(self.masterTab)
		self.SGWindowLabel.setObjectName("SGWindowLabel")
		self.formLayout.setWidget(40, QtWidgets.QFormLayout.LabelRole, self.SGWindowLabel)
		self.SGOrderLabel = QtWidgets.QLabel(self.masterTab)
		self.SGOrderLabel.setObjectName("SGOrderLabel")
		self.formLayout.setWidget(41, QtWidgets.QFormLayout.LabelRole, self.SGOrderLabel)
		self.alphaThresholdLabel = QtWidgets.QLabel(self.masterTab)
		self.alphaThresholdLabel.setObjectName("alphaThresholdLabel")
		self.formLayout.setWidget(45, QtWidgets.QFormLayout.LabelRole, self.alphaThresholdLabel)
		self.fitWindowLabel = QtWidgets.QLabel(self.masterTab)
		self.fitWindowLabel.setObjectName("fitWindowLabel")
		self.formLayout.setWidget(44, QtWidgets.QFormLayout.LabelRole, self.fitWindowLabel)
		self.medianFactorDRLabel = QtWidgets.QLabel(self.masterTab)
		self.medianFactorDRLabel.setObjectName("medianFactorDRLabel")
		self.formLayout.setWidget(43, QtWidgets.QFormLayout.LabelRole, self.medianFactorDRLabel)
		self.minimaWindowDRLabel = QtWidgets.QLabel(self.masterTab)
		self.minimaWindowDRLabel.setObjectName("minimaWindowDRLabel")
		self.formLayout.setWidget(42, QtWidgets.QFormLayout.LabelRole, self.minimaWindowDRLabel)
		self.doDoubleRejectionRO = QtWidgets.QLineEdit(self.masterTab)
		self.doDoubleRejectionRO.setReadOnly(True)
		self.doDoubleRejectionRO.setObjectName("doDoubleRejectionRO")
		self.formLayout.setWidget(39, QtWidgets.QFormLayout.FieldRole, self.doDoubleRejectionRO)
		self.SGWindowRO = QtWidgets.QLineEdit(self.masterTab)
		self.SGWindowRO.setReadOnly(True)
		self.SGWindowRO.setObjectName("SGWindowRO")
		self.formLayout.setWidget(40, QtWidgets.QFormLayout.FieldRole, self.SGWindowRO)
		self.SGOrderRO = QtWidgets.QLineEdit(self.masterTab)
		self.SGOrderRO.setReadOnly(True)
		self.SGOrderRO.setObjectName("SGOrderRO")
		self.formLayout.setWidget(41, QtWidgets.QFormLayout.FieldRole, self.SGOrderRO)
		self.minimaWindowDRRO = QtWidgets.QLineEdit(self.masterTab)
		self.minimaWindowDRRO.setReadOnly(True)
		self.minimaWindowDRRO.setObjectName("minimaWindowDRRO")
		self.formLayout.setWidget(42, QtWidgets.QFormLayout.FieldRole, self.minimaWindowDRRO)
		self.medianFactorDRRO = QtWidgets.QLineEdit(self.masterTab)
		self.medianFactorDRRO.setReadOnly(True)
		self.medianFactorDRRO.setObjectName("medianFactorDRRO")
		self.formLayout.setWidget(43, QtWidgets.QFormLayout.FieldRole, self.medianFactorDRRO)
		self.fitWindowRO = QtWidgets.QLineEdit(self.masterTab)
		self.fitWindowRO.setReadOnly(True)
		self.fitWindowRO.setObjectName("fitWindowRO")
		self.formLayout.setWidget(44, QtWidgets.QFormLayout.FieldRole, self.fitWindowRO)
		self.alphaThresholdRO = QtWidgets.QLineEdit(self.masterTab)
		self.alphaThresholdRO.setReadOnly(True)
		self.alphaThresholdRO.setObjectName("alphaThresholdRO")
		self.formLayout.setWidget(45, QtWidgets.QFormLayout.FieldRole, self.alphaThresholdRO)
		self.PeakFinderLabel = QtWidgets.QLabel(self.masterTab)
		self.PeakFinderLabel.setObjectName("PeakFinderLabel")
		self.formLayout.setWidget(46, QtWidgets.QFormLayout.LabelRole, self.PeakFinderLabel)
		self.minimaWindowPFLabel = QtWidgets.QLabel(self.masterTab)
		self.minimaWindowPFLabel.setObjectName("minimaWindowPFLabel")
		self.formLayout.setWidget(56, QtWidgets.QFormLayout.LabelRole, self.minimaWindowPFLabel)
		self.plotRawLabel = QtWidgets.QLabel(self.masterTab)
		self.plotRawLabel.setObjectName("plotRawLabel")
		self.formLayout.setWidget(47, QtWidgets.QFormLayout.LabelRole, self.plotRawLabel)
		self.convSigLabel = QtWidgets.QLabel(self.masterTab)
		self.convSigLabel.setObjectName("convSigLabel")
		self.formLayout.setWidget(55, QtWidgets.QFormLayout.LabelRole, self.convSigLabel)
		self.convPowerLabel = QtWidgets.QLabel(self.masterTab)
		self.convPowerLabel.setObjectName("convPowerLabel")
		self.formLayout.setWidget(54, QtWidgets.QFormLayout.LabelRole, self.convPowerLabel)
		self.convWindowLabel = QtWidgets.QLabel(self.masterTab)
		self.convWindowLabel.setObjectName("convWindowLabel")
		self.formLayout.setWidget(53, QtWidgets.QFormLayout.LabelRole, self.convWindowLabel)
		self.stdFactorLabel = QtWidgets.QLabel(self.masterTab)
		self.stdFactorLabel.setObjectName("stdFactorLabel")
		self.formLayout.setWidget(52, QtWidgets.QFormLayout.LabelRole, self.stdFactorLabel)
		self.medianFactorPFLabel = QtWidgets.QLabel(self.masterTab)
		self.medianFactorPFLabel.setObjectName("medianFactorPFLabel")
		self.formLayout.setWidget(51, QtWidgets.QFormLayout.LabelRole, self.medianFactorPFLabel)
		self.savePhotonsLabel = QtWidgets.QLabel(self.masterTab)
		self.savePhotonsLabel.setObjectName("savePhotonsLabel")
		self.formLayout.setWidget(50, QtWidgets.QFormLayout.LabelRole, self.savePhotonsLabel)
		self.doPeakFinderLabel = QtWidgets.QLabel(self.masterTab)
		self.doPeakFinderLabel.setObjectName("doPeakFinderLabel")
		self.formLayout.setWidget(49, QtWidgets.QFormLayout.LabelRole, self.doPeakFinderLabel)
		self.photonFilenameLabel = QtWidgets.QLabel(self.masterTab)
		self.photonFilenameLabel.setObjectName("photonFilenameLabel")
		self.formLayout.setWidget(48, QtWidgets.QFormLayout.LabelRole, self.photonFilenameLabel)
		self.plotRawRO = QtWidgets.QLineEdit(self.masterTab)
		self.plotRawRO.setReadOnly(True)
		self.plotRawRO.setObjectName("plotRawRO")
		self.formLayout.setWidget(47, QtWidgets.QFormLayout.FieldRole, self.plotRawRO)
		self.photonFilenameRO = QtWidgets.QLineEdit(self.masterTab)
		self.photonFilenameRO.setReadOnly(True)
		self.photonFilenameRO.setObjectName("photonFilenameRO")
		self.formLayout.setWidget(48, QtWidgets.QFormLayout.FieldRole, self.photonFilenameRO)
		self.doPeakFinderRO = QtWidgets.QLineEdit(self.masterTab)
		self.doPeakFinderRO.setReadOnly(True)
		self.doPeakFinderRO.setObjectName("doPeakFinderRO")
		self.formLayout.setWidget(49, QtWidgets.QFormLayout.FieldRole, self.doPeakFinderRO)
		self.savePhotonsRO = QtWidgets.QLineEdit(self.masterTab)
		self.savePhotonsRO.setReadOnly(True)
		self.savePhotonsRO.setObjectName("savePhotonsRO")
		self.formLayout.setWidget(50, QtWidgets.QFormLayout.FieldRole, self.savePhotonsRO)
		self.medianFactorPFRO = QtWidgets.QLineEdit(self.masterTab)
		self.medianFactorPFRO.setReadOnly(True)
		self.medianFactorPFRO.setObjectName("medianFactorPFRO")
		self.formLayout.setWidget(51, QtWidgets.QFormLayout.FieldRole, self.medianFactorPFRO)
		self.stdFactorRO = QtWidgets.QLineEdit(self.masterTab)
		self.stdFactorRO.setReadOnly(True)
		self.stdFactorRO.setObjectName("stdFactorRO")
		self.formLayout.setWidget(52, QtWidgets.QFormLayout.FieldRole, self.stdFactorRO)
		self.convWindowRO = QtWidgets.QLineEdit(self.masterTab)
		self.convWindowRO.setReadOnly(True)
		self.convWindowRO.setObjectName("convWindowRO")
		self.formLayout.setWidget(53, QtWidgets.QFormLayout.FieldRole, self.convWindowRO)
		self.convPowerRO = QtWidgets.QLineEdit(self.masterTab)
		self.convPowerRO.setReadOnly(True)
		self.convPowerRO.setObjectName("convPowerRO")
		self.formLayout.setWidget(54, QtWidgets.QFormLayout.FieldRole, self.convPowerRO)
		self.convSigRO = QtWidgets.QLineEdit(self.masterTab)
		self.convSigRO.setReadOnly(True)
		self.convSigRO.setObjectName("convSigRO")
		self.formLayout.setWidget(55, QtWidgets.QFormLayout.FieldRole, self.convSigRO)
		self.minimaWindowPFRO = QtWidgets.QLineEdit(self.masterTab)
		self.minimaWindowPFRO.setReadOnly(True)
		self.minimaWindowPFRO.setObjectName("minimaWindowPFRO")
		self.formLayout.setWidget(56, QtWidgets.QFormLayout.FieldRole, self.minimaWindowPFRO)
		self.PhotonCountingLabel = QtWidgets.QLabel(self.masterTab)
		self.PhotonCountingLabel.setObjectName("PhotonCountingLabel")
		self.formLayout.setWidget(57, QtWidgets.QFormLayout.LabelRole, self.PhotonCountingLabel)
		self.photonTitleLabel = QtWidgets.QLabel(self.masterTab)
		self.photonTitleLabel.setObjectName("photonTitleLabel")
		self.formLayout.setWidget(61, QtWidgets.QFormLayout.LabelRole, self.photonTitleLabel)
		self.photonLabelsLabel = QtWidgets.QLabel(self.masterTab)
		self.photonLabelsLabel.setObjectName("photonLabelsLabel")
		self.formLayout.setWidget(60, QtWidgets.QFormLayout.LabelRole, self.photonLabelsLabel)
		self.photonFilesLabel = QtWidgets.QLabel(self.masterTab)
		self.photonFilesLabel.setObjectName("photonFilesLabel")
		self.formLayout.setWidget(59, QtWidgets.QFormLayout.LabelRole, self.photonFilesLabel)
		self.doPhotonCountingLabel = QtWidgets.QLabel(self.masterTab)
		self.doPhotonCountingLabel.setObjectName("doPhotonCountingLabel")
		self.formLayout.setWidget(58, QtWidgets.QFormLayout.LabelRole, self.doPhotonCountingLabel)
		self.doPhotonCountingRO = QtWidgets.QLineEdit(self.masterTab)
		self.doPhotonCountingRO.setReadOnly(True)
		self.doPhotonCountingRO.setObjectName("doPhotonCountingRO")
		self.formLayout.setWidget(58, QtWidgets.QFormLayout.FieldRole, self.doPhotonCountingRO)
		self.photonFilesRO = QtWidgets.QLineEdit(self.masterTab)
		self.photonFilesRO.setReadOnly(True)
		self.photonFilesRO.setObjectName("photonFilesRO")
		self.formLayout.setWidget(59, QtWidgets.QFormLayout.FieldRole, self.photonFilesRO)
		self.photonLabelsRO = QtWidgets.QLineEdit(self.masterTab)
		self.photonLabelsRO.setReadOnly(True)
		self.photonLabelsRO.setObjectName("photonLabelsRO")
		self.formLayout.setWidget(60, QtWidgets.QFormLayout.FieldRole, self.photonLabelsRO)
		self.photonTitleRO = QtWidgets.QLineEdit(self.masterTab)
		self.photonTitleRO.setReadOnly(True)
		self.photonTitleRO.setObjectName("photonTitleRO")
		self.formLayout.setWidget(61, QtWidgets.QFormLayout.FieldRole, self.photonTitleRO)
		self.masterReadout.addTab(self.masterTab, "")
		self.metaTab = QtWidgets.QWidget()
		self.metaTab.setObjectName("metaTab")
		self.formLayout_2 = QtWidgets.QFormLayout(self.metaTab)
		self.formLayout_2.setContentsMargins(0, 0, 0, 0)
		self.formLayout_2.setObjectName("formLayout_2")
		self.GeneralMetaLabel = QtWidgets.QLabel(self.metaTab)
		self.GeneralMetaLabel.setObjectName("GeneralMetaLabel")
		self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.GeneralMetaLabel)
		self.xWidthPhysicalLabel = QtWidgets.QLabel(self.metaTab)
		self.xWidthPhysicalLabel.setObjectName("xWidthPhysicalLabel")
		self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.xWidthPhysicalLabel)
		self.xWidthPhysicalRO = QtWidgets.QLineEdit(self.metaTab)
		self.xWidthPhysicalRO.setReadOnly(True)
		self.xWidthPhysicalRO.setObjectName("xWidthPhysicalRO")
		self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.xWidthPhysicalRO)
		self.xWidthUnitLabel = QtWidgets.QLabel(self.metaTab)
		self.xWidthUnitLabel.setObjectName("xWidthUnitLabel")
		self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.xWidthUnitLabel)
		self.xWidthUnitRO = QtWidgets.QLineEdit(self.metaTab)
		self.xWidthUnitRO.setReadOnly(True)
		self.xWidthUnitRO.setObjectName("xWidthUnitRO")
		self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.xWidthUnitRO)
		self.xLocationLabel = QtWidgets.QLabel(self.metaTab)
		self.xLocationLabel.setObjectName("xLocationLabel")
		self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.xLocationLabel)
		self.xLocationRO = QtWidgets.QLineEdit(self.metaTab)
		self.xLocationRO.setReadOnly(True)
		self.xLocationRO.setObjectName("xLocationRO")
		self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.xLocationRO)
		self.yHeightUnitsLabel = QtWidgets.QLabel(self.metaTab)
		self.yHeightUnitsLabel.setObjectName("yHeightUnitsLabel")
		self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.yHeightUnitsLabel)
		self.yHeightUnitsRO = QtWidgets.QLineEdit(self.metaTab)
		self.yHeightUnitsRO.setReadOnly(True)
		self.yHeightUnitsRO.setObjectName("yHeightUnitsRO")
		self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.yHeightUnitsRO)
		self.triggerLabel = QtWidgets.QLabel(self.metaTab)
		self.triggerLabel.setObjectName("triggerLabel")
		self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.triggerLabel)
		self.triggerRO = QtWidgets.QLineEdit(self.metaTab)
		self.triggerRO.setReadOnly(True)
		self.triggerRO.setObjectName("triggerRO")
		self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.triggerRO)
		self.triggerSourceLabel = QtWidgets.QLabel(self.metaTab)
		self.triggerSourceLabel.setObjectName("triggerSourceLabel")
		self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.triggerSourceLabel)
		self.triggerSourceRO = QtWidgets.QLineEdit(self.metaTab)
		self.triggerSourceRO.setReadOnly(True)
		self.triggerSourceRO.setObjectName("triggerSourceRO")
		self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.triggerSourceRO)
		self.triggerTypeLabel = QtWidgets.QLabel(self.metaTab)
		self.triggerTypeLabel.setObjectName("triggerTypeLabel")
		self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.triggerTypeLabel)
		self.triggerTypeRO = QtWidgets.QLineEdit(self.metaTab)
		self.triggerTypeRO.setReadOnly(True)
		self.triggerTypeRO.setObjectName("triggerTypeRO")
		self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.triggerTypeRO)
		self.sampleLabel = QtWidgets.QLabel(self.metaTab)
		self.sampleLabel.setObjectName("sampleLabel")
		self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.sampleLabel)
		self.sampleRO = QtWidgets.QLineEdit(self.metaTab)
		self.sampleRO.setReadOnly(True)
		self.sampleRO.setObjectName("sampleRO")
		self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.sampleRO)
		self.xDivsLabel = QtWidgets.QLabel(self.metaTab)
		self.xDivsLabel.setObjectName("xDivsLabel")
		self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.xDivsLabel)
		self.xDivsRO = QtWidgets.QLineEdit(self.metaTab)
		self.xDivsRO.setReadOnly(True)
		self.xDivsRO.setObjectName("xDivsRO")
		self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.xDivsRO)
		self.yDivsLabel = QtWidgets.QLabel(self.metaTab)
		self.yDivsLabel.setObjectName("yDivsLabel")
		self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.yDivsLabel)
		self.yDivsRO = QtWidgets.QLineEdit(self.metaTab)
		self.yDivsRO.setReadOnly(True)
		self.yDivsRO.setObjectName("yDivsRO")
		self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.yDivsRO)
		self.Channel1Label = QtWidgets.QLabel(self.metaTab)
		self.Channel1Label.setObjectName("Channel1Label")
		self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.Channel1Label)
		self.object1Label = QtWidgets.QLabel(self.metaTab)
		self.object1Label.setObjectName("object1Label")
		self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.object1Label)
		self.object1RO = QtWidgets.QLineEdit(self.metaTab)
		self.object1RO.setReadOnly(True)
		self.object1RO.setObjectName("object1RO")
		self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.object1RO)
		self.inputImpedence1Label = QtWidgets.QLabel(self.metaTab)
		self.inputImpedence1Label.setObjectName("inputImpedence1Label")
		self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.inputImpedence1Label)
		self.inputImpedence1RO = QtWidgets.QLineEdit(self.metaTab)
		self.inputImpedence1RO.setReadOnly(True)
		self.inputImpedence1RO.setObjectName("inputImpedence1RO")
		self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.inputImpedence1RO)
		self.coupling1Label = QtWidgets.QLabel(self.metaTab)
		self.coupling1Label.setObjectName("coupling1Label")
		self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.coupling1Label)
		self.coupling1RO = QtWidgets.QLineEdit(self.metaTab)
		self.coupling1RO.setReadOnly(True)
		self.coupling1RO.setObjectName("coupling1RO")
		self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.coupling1RO)
		self.offset1Label = QtWidgets.QLabel(self.metaTab)
		self.offset1Label.setObjectName("offset1Label")
		self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.offset1Label)
		self.offset1RO = QtWidgets.QLineEdit(self.metaTab)
		self.offset1RO.setReadOnly(True)
		self.offset1RO.setObjectName("offset1RO")
		self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.offset1RO)
		self.bandwidth1Label = QtWidgets.QLabel(self.metaTab)
		self.bandwidth1Label.setObjectName("bandwidth1Label")
		self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.bandwidth1Label)
		self.bandwidth1RO = QtWidgets.QLineEdit(self.metaTab)
		self.bandwidth1RO.setReadOnly(True)
		self.bandwidth1RO.setObjectName("bandwidth1RO")
		self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.bandwidth1RO)
		self.VoltsPerDiv1Label = QtWidgets.QLabel(self.metaTab)
		self.VoltsPerDiv1Label.setObjectName("VoltsPerDiv1Label")
		self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.VoltsPerDiv1Label)
		self.VoltsPerDiv1RO = QtWidgets.QLineEdit(self.metaTab)
		self.VoltsPerDiv1RO.setReadOnly(True)
		self.VoltsPerDiv1RO.setObjectName("VoltsPerDiv1RO")
		self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.VoltsPerDiv1RO)
		self.yLocation1Label = QtWidgets.QLabel(self.metaTab)
		self.yLocation1Label.setObjectName("yLocation1Label")
		self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.yLocation1Label)
		self.yLocation1RO = QtWidgets.QLineEdit(self.metaTab)
		self.yLocation1RO.setReadOnly(True)
		self.yLocation1RO.setObjectName("yLocation1RO")
		self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.yLocation1RO)
		self.Channel2Label = QtWidgets.QLabel(self.metaTab)
		self.Channel2Label.setObjectName("Channel2Label")
		self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.Channel2Label)
		self.object2Label = QtWidgets.QLabel(self.metaTab)
		self.object2Label.setObjectName("object2Label")
		self.formLayout_2.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.object2Label)
		self.object2RO = QtWidgets.QLineEdit(self.metaTab)
		self.object2RO.setReadOnly(True)
		self.object2RO.setObjectName("object2RO")
		self.formLayout_2.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.object2RO)
		self.inputImpedence2Label = QtWidgets.QLabel(self.metaTab)
		self.inputImpedence2Label.setObjectName("inputImpedence2Label")
		self.formLayout_2.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.inputImpedence2Label)
		self.inputImpedence2RO = QtWidgets.QLineEdit(self.metaTab)
		self.inputImpedence2RO.setReadOnly(True)
		self.inputImpedence2RO.setObjectName("inputImpedence2RO")
		self.formLayout_2.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.inputImpedence2RO)
		self.coupling2Label = QtWidgets.QLabel(self.metaTab)
		self.coupling2Label.setObjectName("coupling2Label")
		self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.coupling2Label)
		self.coupling2RO = QtWidgets.QLineEdit(self.metaTab)
		self.coupling2RO.setReadOnly(True)
		self.coupling2RO.setObjectName("coupling2RO")
		self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.coupling2RO)
		self.offset2Label = QtWidgets.QLabel(self.metaTab)
		self.offset2Label.setObjectName("offset2Label")
		self.formLayout_2.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.offset2Label)
		self.offset2RO = QtWidgets.QLineEdit(self.metaTab)
		self.offset2RO.setReadOnly(True)
		self.offset2RO.setObjectName("offset2RO")
		self.formLayout_2.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.offset2RO)
		self.bandwidth2Label = QtWidgets.QLabel(self.metaTab)
		self.bandwidth2Label.setObjectName("bandwidth2Label")
		self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.bandwidth2Label)
		self.bandwidth2RO = QtWidgets.QLineEdit(self.metaTab)
		self.bandwidth2RO.setReadOnly(True)
		self.bandwidth2RO.setObjectName("bandwidth2RO")
		self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.bandwidth2RO)
		self.VoltsPerDiv2Label = QtWidgets.QLabel(self.metaTab)
		self.VoltsPerDiv2Label.setObjectName("VoltsPerDiv2Label")
		self.formLayout_2.setWidget(25, QtWidgets.QFormLayout.LabelRole, self.VoltsPerDiv2Label)
		self.VoltsPerDiv2RO = QtWidgets.QLineEdit(self.metaTab)
		self.VoltsPerDiv2RO.setReadOnly(True)
		self.VoltsPerDiv2RO.setObjectName("VoltsPerDiv2RO")
		self.formLayout_2.setWidget(25, QtWidgets.QFormLayout.FieldRole, self.VoltsPerDiv2RO)
		self.yLocation2Label = QtWidgets.QLabel(self.metaTab)
		self.yLocation2Label.setObjectName("yLocation2Label")
		self.formLayout_2.setWidget(26, QtWidgets.QFormLayout.LabelRole, self.yLocation2Label)
		self.yLocation2RO = QtWidgets.QLineEdit(self.metaTab)
		self.yLocation2RO.setReadOnly(True)
		self.yLocation2RO.setObjectName("yLocation2RO")
		self.formLayout_2.setWidget(26, QtWidgets.QFormLayout.FieldRole, self.yLocation2RO)
		self.masterReadout.addTab(self.metaTab, "")
		self.gridLayout.addWidget(self.masterReadout, 0, 0, 1, 1)
		self.scrollArea.setWidget(self.scrollAreaWidgetContents)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 20))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		self.masterReadout.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.masterLabel.setText(_translate("MainWindow", "Master"))
		self.BrowseButton.setText(_translate("MainWindow", "Browse"))
		self.LoadButton.setText(_translate("MainWindow", "Load"))
		self.GeneralLabel.setText(_translate("MainWindow", "<b>General</b>"))
		self.workingDirLabel.setText(_translate("MainWindow", "Working Directory"))
		self.dataDirLabel.setText(_translate("MainWindow", "Data Directory"))
		self.plotsDirLabel.setText(_translate("MainWindow", "Plots Directory"))
		self.traceDirLabel.setText(_translate("MainWindow", "Trace Directory"))
		self.ansiColorsLabel.setText(_translate("MainWindow", "ANSI Colors"))
		self.doPlotsLabel.setText(_translate("MainWindow", "doPlots"))
		self.IOLabel.setText(_translate("MainWindow", "<b>IO</b>"))
		self.saveDataLabel.setText(_translate("MainWindow", "Save Data"))
		self.saveToLabel.setText(_translate("MainWindow", "Save To"))
		self.loadLabel.setText(_translate("MainWindow", "Load Data"))
		self.loadFromLabel.setText(_translate("MainWindow", "Load From"))
		self.showPlotsLabel.setText(_translate("MainWindow", "Show plots"))
		self.savePlotsLabel.setText(_translate("MainWindow", "Save Plots"))
		self.allPlotsLabel.setText(_translate("MainWindow", "Do All Plots"))
		self.ChannelLabel.setText(_translate("MainWindow", "<b>Channels</b>"))
		self.doubleChannelLabel.setText(_translate("MainWindow", "Two Channels"))
		self.BGSubtractionLabel.setText(_translate("MainWindow", "BG Subtraction"))
		self.channel1Label.setText(_translate("MainWindow", "Channel 1"))
		self.channel2Label.setText(_translate("MainWindow", "Channel 2"))
		self.metaLabel.setText(_translate("MainWindow", "Meta File"))
		self.channelBGLabel.setText(_translate("MainWindow", "BG Channel 1"))
		self.channel2BGLabel.setText(_translate("MainWindow", "BG Meta"))
		self.metaBG.setText(_translate("MainWindow", "BG Channel 2"))
		self.WindowLabel.setText(_translate("MainWindow", "<b>Window</b>"))
		self.xPlotTypeLabel.setText(_translate("MainWindow", "X Plot Type"))
		self.yPlotTypeLabel.setText(_translate("MainWindow", "Y Plot Type"))
		self.xRelativeGridLabel.setText(_translate("MainWindow", "X Relative Grid"))
		self.IntegrationLabel.setText(_translate("MainWindow", "<b>Integration</b>"))
		self.SILLabel.setText(_translate("MainWindow", "Signal Int. Lower"))
		self.SIULabel.setText(_translate("MainWindow", "Signal Int. Upper"))
		self.PILLabel.setText(_translate("MainWindow", "Pedestal Int. Lower"))
		self.PIULabel.setText(_translate("MainWindow", "Pedestal Int. Upper"))
		self.SpikeRejectionLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Spike Rejection</span></p></body></html>"))
		self.doSpikeRejectionLabel.setText(_translate("MainWindow", "Do Rejection"))
		self.voltageThreshholdLabel.setText(_translate("MainWindow", "Voltage Thresh."))
		self.timeThresholdLabel.setText(_translate("MainWindow", "Time Thresh."))
		self.SmoothedDoubleRejectionLabel.setText(_translate("MainWindow", "<b>Double Rejection</b>."))
		self.doDoubleRejectionLabel.setText(_translate("MainWindow", "Do Rejection"))
		self.SGWindowLabel.setText(_translate("MainWindow", "S-G Window"))
		self.SGOrderLabel.setText(_translate("MainWindow", "S-G Order"))
		self.alphaThresholdLabel.setText(_translate("MainWindow", "Alpha Thresh."))
		self.fitWindowLabel.setText(_translate("MainWindow", "Fit Window"))
		self.medianFactorDRLabel.setText(_translate("MainWindow", "Median Factor"))
		self.minimaWindowDRLabel.setText(_translate("MainWindow", "Minima Window"))
		self.PeakFinderLabel.setText(_translate("MainWindow", "<b>Peak Finder</b>"))
		self.minimaWindowPFLabel.setText(_translate("MainWindow", "Minima Window"))
		self.plotRawLabel.setText(_translate("MainWindow", "Plot Raw"))
		self.convSigLabel.setText(_translate("MainWindow", "Conv. Sig"))
		self.convPowerLabel.setText(_translate("MainWindow", "Conv. Power"))
		self.convWindowLabel.setText(_translate("MainWindow", "Conv. Window"))
		self.stdFactorLabel.setText(_translate("MainWindow", "Stand. Dev. Factor"))
		self.medianFactorPFLabel.setText(_translate("MainWindow", "Median Factor"))
		self.savePhotonsLabel.setText(_translate("MainWindow", "Save Output"))
		self.doPeakFinderLabel.setText(_translate("MainWindow", "Do Peak Finding"))
		self.photonFilenameLabel.setText(_translate("MainWindow", "Save Name"))
		self.PhotonCountingLabel.setText(_translate("MainWindow", "<b>Photon Counting</b>"))
		self.photonTitleLabel.setText(_translate("MainWindow", "Photon Title"))
		self.photonLabelsLabel.setText(_translate("MainWindow", "Photon Labels"))
		self.photonFilesLabel.setText(_translate("MainWindow", "Photon Files"))
		self.doPhotonCountingLabel.setText(_translate("MainWindow", "Do Photon Counting"))
		self.masterReadout.setTabText(self.masterReadout.indexOf(self.masterTab), _translate("MainWindow", "Master"))
		self.GeneralMetaLabel.setText(_translate("MainWindow", "<b>General</b>"))
		self.xWidthPhysicalLabel.setText(_translate("MainWindow", "xWidthPhysical"))
		self.xWidthUnitLabel.setText(_translate("MainWindow", "xWidthUnit"))
		self.xLocationLabel.setText(_translate("MainWindow", "xLocation"))
		self.yHeightUnitsLabel.setText(_translate("MainWindow", "yHeightUnits"))
		self.triggerLabel.setText(_translate("MainWindow", "trigger"))
		self.triggerSourceLabel.setText(_translate("MainWindow", "triggerSource"))
		self.triggerTypeLabel.setText(_translate("MainWindow", "triggerType"))
		self.sampleLabel.setText(_translate("MainWindow", "sample"))
		self.xDivsLabel.setText(_translate("MainWindow", "xDivs"))
		self.yDivsLabel.setText(_translate("MainWindow", "yDivs"))
		self.Channel1Label.setText(_translate("MainWindow", "<b>Channel 1</b>"))
		self.object1Label.setText(_translate("MainWindow", "object"))
		self.inputImpedence1Label.setText(_translate("MainWindow", "inputImpedence"))
		self.coupling1Label.setText(_translate("MainWindow", "coupling"))
		self.offset1Label.setText(_translate("MainWindow", "offset"))
		self.bandwidth1Label.setText(_translate("MainWindow", "bandwidth"))
		self.VoltsPerDiv1Label.setText(_translate("MainWindow", "VoltsPerDiv"))
		self.yLocation1Label.setText(_translate("MainWindow", "yLocation"))
		self.Channel2Label.setText(_translate("MainWindow", "<b>Channel 2</b>"))
		self.object2Label.setText(_translate("MainWindow", "object"))
		self.inputImpedence2Label.setText(_translate("MainWindow", "inputImpedence"))
		self.coupling2Label.setText(_translate("MainWindow", "coupling"))
		self.offset2Label.setText(_translate("MainWindow", "offset"))
		self.bandwidth2Label.setText(_translate("MainWindow", "bandwidth"))
		self.VoltsPerDiv2Label.setText(_translate("MainWindow", "VoltsPerDiv"))
		self.yLocation2Label.setText(_translate("MainWindow", "yLocation"))
		self.masterReadout.setTabText(self.masterReadout.indexOf(self.metaTab), _translate("MainWindow", "Meta"))

